### ISSUE TITLE
netlinks

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#22]
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_M56qFF/ansible_module_network_element.py", line 642, in <module>
    main()
  File "/tmp/ansible_M56qFF/ansible_module_network_element.py", line 639, in main
    NetworkElement()
  File "/tmp/ansible_M56qFF/ansible_module_network_element.py", line 449, in __init__
    super(NetworkElement, self).__init__(self.module_args, supports_check_mode=True)
  File "/tmp/ansible_M56qFF/ansible_modlib.zip/ansible/module_utils/stonesoft_util.py", line 449, in __init__
  File "/tmp/ansible_M56qFF/ansible_module_network_element.py", line 534, in exec_module
    _netlink, ELEMENT_TYPES, check_mode=self.check_mode)
  File "/tmp/ansible_M56qFF/ansible_modlib.zip/ansible/module_utils/stonesoft_util.py", line 305, in update_or_create
  File "/usr/lib/python2.7/site-packages/smc_python-0.6.1_dev.201802262117-py2.7.egg/smc/elements/netlink.py", line 172, in update_or_create
    kwargs.pop('domain_server_address', []))
  File "/usr/lib/python2.7/site-packages/smc_python-0.6.1_dev.201802262117-py2.7.egg/smc/core/general.py", line 279, in append
    self._rank_dns(values)
  File "/usr/lib/python2.7/site-packages/smc_python-0.6.1_dev.201802262117-py2.7.egg/smc/core/general.py", line 245, in _rank_dns
    for e in entry:
**TypeError: 'NoneType' object is not iterable**

**configuration**
_- name: Create netlinks ENT_MPLS
  register: result
  network_element:
      smc_logging:
        level: 10
        path: ansible-smc.log
      elements:
      - netlink:
            name: ENT_MPLS
            gateway:
                name: ENT_RTR-MPLS
                type: router
            network:
                -  ENT_Wan-Local
            domain_server_address:
            probe_address:
                -   10.1.2.3
            comment: added by  API_

**Comment by meandus** [comment]
object is already exists ... first time was ok , second time was not correct (NoneType)

**Comment by gabstopper** [comment]
Ok, added validation. Will update once update is deployed. I want to look at the other requests and try to incorporate any changes needed there as well.

**Comment by gabstopper** [comment]
This should be addressed in the latest development branch that was posted last night. Please confirm this now works for you.

**Comment by gabstopper** [comment]
addressed in latest smc-python 0.6.1 and newer
